spring.application.name=AgroGestao

spring.application.name=AgroGestao

spring.datasource.url=jdbc:mysql://localhost:3306/agrogestao
spring.datasource.username=root
spring.datasource.password=agro123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true